pointfreeco/swift-custom-dump

.github/workflows/ci.yml, .swiftpm/xcode/xcshareddata/xcschemes/CustomDump_watchOS.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/swift-custom-dump.xcscheme, Makefile, Sources/CustomDump/Conformances/CoreMotion.swift, Sources/CustomDump/Conformances/GameKit.swift, Sources/CustomDump/Diff.swift, Tests/CustomDumpTests/DiffTests.swift, Tests/CustomDumpTests/DumpTests.swift
We'll now run tests on all Apple platforms and build for release on all platforms.
=> Improve CI coverage

Sources/CustomDump/Conformances/UIKit.swift
Noticed this because we use it in isowords state.
=> Add UIUserInterfaceStyle conformance

Sources/CustomDump/Conformances/UIKit.swift, Tests/CustomDumpTests/Conformances/UIKitTests.swift
Because it is widely used.
And, I added a sample tests for UIKit. 
I think that this is important for added enumeration case in the future. (like a unknown default)
=> Add UIControl.State conformance

Sources/CustomDump/Conformances/Foundation.swift, Tests/CustomDumpTests/DumpTests.swift
```swift
customDump(NSDecimalNumber(string: "1.23"))
customDump(Decimal(string: "1.23"))
```
Before:
```
1.23
NSDecimal(
_mantissa: (
123,
0,
0,
0,
0,
0,
0,
0
)
)
```
After:
```
1.23
1.23
```
---
Note: Swift.dump
```swift
dump(NSDecimalNumber(string: "1.23"))
dump(Decimal(string: "1.23"))
```
```
- 1.23 #0
- super: NSNumber
- super: NSValue
- super: NSObject
▿ Optional(1.23)
▿ some: 1.23
▿ _mantissa: (8 elements)
- .0: 123
- .1: 0
- .2: 0
- .3: 0
- .4: 0
- .5: 0
- .6: 0
- .7: 0
```
=> Add Decimal conformance

Sources/CustomDump/Conformances/CoreImage.swift, Tests/CustomDumpTests/Conformances/CoreImageTests.swift
I extended some CoreImage conformance
=> Extend CoreImage conformance 

Sources/CustomDump/Conformances/Foundation.swift, Tests/CustomDumpTests/DumpTests.swift
When dumping a Swift Error bridged to NSError, we'd only show the error
domain and error code generated by the Swift runtime. We can get much
better output (e.g., enum/case names, associated values, etc.) if we
unwrap the Swift Error and dump it directly.
=> Improve dumping of Errors bridged to NSError

.github/workflows/ci.yml, Tests/CustomDumpTests/DumpTests.swift
I recently added tests for the Windows platform on a tool using this library and it failed while running this libraries manifest file. Thus I believe it's probably a good idea to test for Windows support right within this repo.
The exact command that hung up for 6 hours was:
```
C:\Users\runneradmin\AppData\Local\Temp\TemporaryDirectory.vFcVbW\swift-custom-dump-manifest.exe -handle 674
```
Here's the GitHub Actions run with the full test output:
https://github.com/Flinesoft/AnyLint/runs/3576556438?check_suite_focus=true
=> Add Windows testing support on CI

Sources/CustomDump/Conformances/Foundation.swift, Sources/CustomDump/Conformances/UserNotifications.swift
When compiling this library for mac catalyst, a couple symbols are still not available in that platform/environment combination, and compiler errors show up as a result. This PR will opt to avoid compiling those symbols when in mac catalyst mode in Xcode 13.
=> Don't compile symbols for mac catalyst that are not yet available out of beta

Sources/CustomDump/Conformances/Foundation.swift, Tests/CustomDumpTests/DumpTests.swift
Basically the same as #20 but for Linux this time. This PR fixes Swift 5.5 compilation on Linux.
Backstory: Swift 5.5 images don't come bundled with a version of Foundation containing `AttributedString` yet. Whilst the changes are [in the upstream branch](https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/AttributedString/AttributedString.swift), a release hasn't been made yet — I believe because macOS 12 is not out yet and Apple wants parity with "Apple Foundation".
=> Don't compile symbols for Linux that are not yet available

Makefile, Tests/CustomDumpTests/DumpTests.swift
Seeing #20 makes me think we should run catalyst tests on CI. This should fail until #20 merges to main and is then merged into this branch.
=> Run CI tests on Mac Catalyst.

Tests/CustomDumpTests/DumpTests.swift
Makes the test's `#if` logic match that of the logic in Foundation.swift.
=> Check catalyst in AttributedString tests.

Sources/CustomDump/Conformances/UserNotifications.swift
Xcode 13.2 introduced a new build system that seems to have troubles with availability checks in getters.
https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes
Seeing ~30% speedup with this setting, it's kind of a bummer it can't be turned on with projects using TCA 😞 
Moving the check out of the getter fixes the compile issue.
This solution may not be the PointFree way 😸
=> UNNotificationPresentationOptions [.banner, .list] workaround

.github/workflows/ci.yml, Sources/CustomDump/Conformances/UserNotifications.swift
Loosening the platform constraint meant the same kind of experimental build system bugs that were fixed in #30 were introduced all over again.
This PR includes new workarounds and should conditionally run CI against the new build system, as well.
=> Run 13.2 CI on experimental build system

.github/CODE_OF_CONDUCT.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md
Templates help provide additional context when bugs are submitted in our other repos, so let's add them here.
=> Add issue templates and CoC

Sources/CustomDump/Internal/AnyType.swift
Small thing I noticed. We're relying on a strange implicit behavior of `String.init(reflecting:)`, but the standard library has an ABI-stable `_typeName` function we can rely on instead.
=> Use `_typeName` instead of `String.init(reflecting:)`

Sources/CustomDump/Conformances/Foundation.swift
Related:
- https://github.com/pointfreeco/xctest-dynamic-overlay/pull/31
This PR adds `if !os(WASI)` for the scopes where some of the Foundation classes don't work in SwiftWasm.
[Porting code from other platforms - Swift and WebAssembly](https://book.swiftwasm.org/getting-started/porting.html#swift-foundation-and-dispatch)
=> Add `if !os(WASI)` for SwiftWasm

Sources/CustomDump/Dump.swift, Tests/CustomDumpTests/DumpTests.swift
Adding a unique id for occurrences of the same type.
**Motivation**
- Whenever the same object is repeated within a dump it gets completely redacted. This is done to avoid recursion but it can also mean that if there is the same object the appears multiple times for other reasons it still gets redacted
- If there is a repetition of multiple objects of the same type it removes the information about which object it is in the redacted state
- By assigning an id to each second or more occurrence of the same type we can identify which object it is easily
=> Add ids to second occurrence of a type within a dump

.github/workflows/ci.yml, Makefile, Sources/CustomDump/Conformances/KeyPath.swift, Tests/CustomDumpTests/XCTAssertNoDifferenceTests.swift
Some CI updates to better test #67 and prep a fix.
=> Update CI to use latest Xcode, test in release

Sources/CustomDump/Dump.swift, Tests/CustomDumpTests/Conformances/FoundationTests.swift, Tests/CustomDumpTests/DumpTests.swift, Tests/CustomDumpTests/Mocks.swift
We can use dot-abbreviation to keep descriptions short but provide enough context.
=> Abbreviate nested enums

Sources/CustomDump/Conformances/SwiftUI.swift, Sources/CustomDump/Diff.swift, Sources/CustomDump/Dump.swift, Sources/CustomDump/Internal/Box.swift, Sources/CustomDump/Internal/String.swift, Tests/CustomDumpTests/DiffTests.swift, Tests/CustomDumpTests/DumpTests.swift, Tests/CustomDumpTests/Mocks.swift
We added the ability to abbreviate nested dumps in #71, but this didn't transfer to diffs.
=> Abbreviate enums in diffs

Sources/CustomDump/Conformances/KeyPath.swift, Sources/CustomDump/Internal/AnyType.swift, Tests/CustomDumpTests/DiffTests.swift, Tests/CustomDumpTests/DumpTests.swift, Tests/CustomDumpTests/Mocks.swift
New in Swift 5.8 with implementation of [SE-0369](https://github.com/apple/swift-evolution/blob/main/proposals/0369-add-customdebugdescription-conformance-to-anykeypath.md).
=> Use `AnyKeyPath.customDebugDescription` when possible

Sources/CustomDump/Conformances/KeyPath.swift, Sources/CustomDump/Internal/AnyType.swift, Tests/CustomDumpTests/DumpTests.swift
The regular expression that strips excessive info from type names was refactored in #73 to fix some bugs that were discovered, but this change caused a regression in some nested types.
=> Fix regression in `typeName` output

Sources/CustomDump/Internal/AnyType.swift, Tests/CustomDumpTests/DumpTests.swift
We try our best to pretty-print in a Swift-y fashion, so let's extend that to the shorthand syntaxes for optionals, arrays, and dictionaries.
=> Abbreviate optional, array, and dictionary types

Sources/CustomDump/Dump.swift, Tests/CustomDumpTests/DumpTests.swift
It can be useful to get a custom dump representation of a value as a string on a single line. Swift provides `String.init(describing:)` and `String.init(reflecting:)` (though no equivalent for a quick string from `Swift.dump`), so maybe we can provide _similar_ functionality via a string initializer.
=> Add `String.init(customDumping:)`

Sources/CustomDump/Diff.swift, Sources/CustomDump/Dump.swift, Sources/CustomDump/Internal/Unordered.swift, Tests/CustomDumpTests/DiffTests.swift, Tests/CustomDumpTests/DumpTests.swift, Tests/CustomDumpTests/Mocks.swift
We currently auto-sort the children of any mirror with a display style of dictionary or set alphabetically. This is important for consistent dumps (good for snapshot tests, too), but affects types that don't need the sorting, like ordered dictionaries and sets.
This PR introduces an `_UnorderedCollection` protocol to control this behavior, and conforms `Dictionary`, `Set`, and their `NS`- predecessors, but leaves other types open to dumping and diffing in an ordered way by default.
=> Support ordered dictionaries/sets

Sources/CustomDump/Dump.swift, Tests/CustomDumpTests/DiffTests.swift
When we reach a custom dump representable value, we should not decrement the max depth when printing it, and instead we should pass the current configuration through.
The current behavior can cause the max depth to roll from 0 to -1, which currently causes the logic that collapses nodes to leave them expanded.
We should update that logic, as well, to collapse whenever <= 0, so I'll do that in another commit.
=> Fix `CustomDumpRepresentable` max depth

.github/workflows/ci.yml, Sources/CustomDump/Conformances/Swift.swift, Sources/CustomDump/Dump.swift, Tests/CustomDumpTests/DumpTests.swift
Could tweak it a bit, but better than the default.
=> Add dump format for Duration

Sources/CustomDump/Conformances/KeyPath.swift
The Swift runtime crash is now fixed, so we can print key paths again in 5.9+.
=> Restore key path debug description in 5.9

Sources/CustomDump/XCTAssertDifference.swift, Tests/CustomDumpTests/XCTAssertDifferenceTests.swift
An idea I brought up here: https://github.com/pointfreeco/swift-composable-architecture/pull/1149#discussion_r898464743
=> Add `XCTAssertDifference` for exhaustively testing changes to values

.github/workflows/ci.yml
We want to start running Windows CI to ensure that no breakage happens on the Windows platform.
=> Turn Windows CI back on

Sources/CustomDump/Diff.swift, Sources/CustomDump/Dump.swift, Tests/CustomDumpTests/DiffTests.swift, Tests/CustomDumpTests/DumpTests.swift
This seems to be the macro convention, and as folks add `@Observable` to their types they will begin to see these details leaking into their dumps, which is generally not relevant and doesn't result in a dump that resembles the original source.
We could consider a configuration option in the future to dump these values, but for now folks can always use plain `dump` or a mirror to access these values when they need them.
=> Filter properties prefixed with `_$`

Sources/CustomDump/Conformances/CoreLocation.swift
`xrOS` no longer gates for availability checks as of visionOS 1.0 beta 6. This PR replaces it with the new os name: `visionOS`
=> Update for visionOS beta 6

Sources/CustomDump/Diff.swift, Sources/CustomDump/Internal/Mirror.swift, Tests/CustomDumpTests/DiffTests.swift
Object references aren't copyable, so objects aren't "diffable" by default. This PR adds experimental support for objects that can be diffed by allowing them to describe the difference.
=> Add experimental support for "diffable" objects

Sources/CustomDump/Conformances/KeyPath.swift
A SIL function we load seems to be unavailable, so let's limit old key path printing to DEBUG builds.
Fixes #107.
=> Fix Xcode 15.3 Release Crash

.github/workflows/ci.yml
`swiftwasm/swiftwasm-action` is now deprecated and replaced by `swiftwasm/setup-swiftwasm`. This change updates the CI workflow to use the new action.
=> Use `swiftwasm/setup-swiftwasm` instead of `swiftwasm/swiftwasm-action`

Package@swift-5.9.swift, Sources/CustomDump/Diff.swift
We've got just one tiny sendable warning in this library so fixing it.
=> Fix sendable warnings.

Sources/CustomDump/Conformances/Foundation.swift
This fixes a Swift 6 compile error (on Linux):
```
/host/Sources/CustomDump/Conformances/Foundation.swift:50:24: error: static property 'formatter' is not concurrency-safe because non-'Sendable' type 'DateFormatter' may have shared mutable state
48 |     }
49 | 
50 |     private static let formatter: DateFormatter = {
|                        `- error: static property 'formatter' is not concurrency-safe because non-'Sendable' type 'DateFormatter' may have shared mutable state
51 |       let formatter = DateFormatter()
52 |       formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX"
```
See also: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3115#issuecomment-2153037172
=> Fix Swift 6 concurrency error (on Linux)

.github/workflows/ci.yml
=> CI: Avoid stack overflow on Wasm tests by extending the stack size

.github/workflows/ci.yml, Sources/CustomDump/Internal/Mirror.swift, Tests/CustomDumpTests/DiffTests.swift
=> Fix infinite loop when diffing non-equatable recursive objects
